from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import anthropic
from core.config import get_settings
from core.cache import cache_get, cache_set

router = APIRouter(prefix="/api/ai", tags=["ai"])
settings = get_settings()


class AnalysisRequest(BaseModel):
    symbol: str
    signal: dict          # Full SignalResult dict from /api/signals
    candle_summary: str = ""   # Optional: "Last 5 candles: …"


SYSTEM_PROMPT = """You are a professional ICT (Inner Circle Trader) forex analyst.
You analyse signals generated by an automated ICT + Technical Analysis engine and provide:
1. A clear directional bias with reasoning
2. Key price levels to watch
3. Risk considerations
4. Whether the signal aligns with the higher timeframe narrative
5. A confidence assessment (agree / partially agree / disagree) with the engine's signal

Keep responses concise — 150–200 words max. Use professional but accessible language.
Do not give financial advice. Always mention this is educational/informational only."""


def build_prompt(req: AnalysisRequest) -> str:
    sig = req.signal
    return f"""Analyse this automated ICT signal:

Pair: {sig.get('symbol')}
Signal: {sig.get('direction')} | Confidence: {sig.get('confidence')}%
Trend: {sig.get('trend')}
Entry: {sig.get('entry')} | SL: {sig.get('stop_loss')} | TP: {sig.get('take_profit')}
R:R Ratio: 1:{sig.get('rr_ratio')}
SL pips: {sig.get('sl_pips')} | TP pips: {sig.get('tp_pips')}

Confluence factors detected:
{chr(10).join(f'  • {f}' for f in sig.get('confluence_factors', []))}

Kill Zone: {sig.get('kill_zone')} ({'active' if sig.get('kill_zone_active') else 'inactive'})
FVG detected: {sig.get('fvg_detected')} ({sig.get('fvg_direction')})
Order Block hit: {sig.get('order_block_hit')}
Fib OTE zone: {sig.get('near_fib_ote')}
Swing High: {sig.get('swing_high')} | Swing Low: {sig.get('swing_low')}
Fib 61.8%: {sig.get('fib_618')} | Fib 78.6%: {sig.get('fib_786')}

{f'Additional context: {req.candle_summary}' if req.candle_summary else ''}

Provide your ICT analysis."""


@router.post("/analyze")
async def analyze_signal(req: AnalysisRequest):
    """
    Send a signal to Claude for natural language ICT analysis.
    Cached for 2 minutes per unique signal fingerprint.
    """
    sig = req.signal
    cache_key = f"ai:{sig.get('symbol')}:{sig.get('direction')}:{sig.get('confidence')}:{sig.get('entry')}"
    cached = await cache_get(cache_key)
    if cached:
        return {"source": "cache", "analysis": cached}

    if not settings.anthropic_api_key:
        raise HTTPException(status_code=503, detail="ANTHROPIC_API_KEY not configured")

    client = anthropic.Anthropic(api_key=settings.anthropic_api_key)

    try:
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=400,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": build_prompt(req)}],
        )
        analysis_text = message.content[0].text
    except anthropic.APIError as e:
        raise HTTPException(status_code=502, detail=f"Claude API error: {e}")

    result = {
        "symbol": sig.get("symbol"),
        "analysis": analysis_text,
        "model": message.model,
        "input_tokens": message.usage.input_tokens,
        "output_tokens": message.usage.output_tokens,
    }

    await cache_set(cache_key, result, ttl=120)
    return {"source": "live", "analysis": result}
